CREATE TABLE IF NOT EXISTS Users
(
	UserID INT NOT NULL PRIMARY KEY,
	PlaylistsID INT[],
	Name VARCHAR(30),
	Surame VARCHAR(30),
	Login VARCHAR(30),
	Password VARCHAR(30),
	AccessLevel INT
);

CREATE TABLE IF NOT EXISTS Playlist
(
	PlaylistID INT NOT NULL PRIMARY KEY,
	SongsID INT[],
	Title VARCHAR(30)
);

CREATE TABLE IF NOT EXISTS Song
(
	SongID INT NOT NULL PRIMARY KEY,
	Title VARCHAR(30),
	Duration VARCHAR(30),
	Author VARCHAR(30),
	Album VARCHAR(30),
	Genre VARCHAR(30),
	Year INT
);

CREATE TABLE IF NOT EXISTS Likes
(
	LikeID INT NOT NULL PRIMARY KEY,
	LikeFrom INT,
	LikeTo INT
);

CREATE TABLE IF NOT EXISTS Chat
(
	ChatID INT NOT NULL PRIMARY KEY,
	User1ID INT,
	User2ID INT
);

CREATE TABLE IF NOT EXISTS Channel
(
	ChannelID INT NOT NULL PRIMARY KEY,
	AdminID INT,
	Subscribers INT,
	Title VARCHAR(30)
);

