INSERT INTO mus_song(title, artist, duration, url, year, album, genre)
VALUES
    ('Gare du Nord', 'Claire Laffut', '3.15', '/media/music/Claire Laffut - Gare du Nord.mp3', 2000, 'unknown1', 'metalcore'),
    ('La fessée', 'Claire Laffut', '3.15', '/media/music/Claire Laffut - La fessée.mp3', 2000, 'unknown1', 'metalcore'),
    ('Mojo', 'Claire Laffut', '3.15', '/media/music/Claire Laffut - Mojo.mp3', 2000, 'unknown1', 'metalcore'),
    ('Vérité', 'Claire Laffut', '3.15', '/media/music/Claire Laffut - Vérité.mp3', 2000, 'unknown1', 'metalcore'),
    ('Humility (feat', 'Gorillaz', '2.15', '/media/music/Gorillaz - Humility (feat. George Benson).mp3', 2001, 'unknown2', 'pop'),
    ('Lake Zurich', 'Gorillaz', '2.15', '/media/music/Gorillaz - Lake Zurich.mp3', 2001, 'unknown2', 'pop'),
    ('Saturnz Barz', 'Gorillaz', '2.15', '/media/music/Gorillaz - Saturnz Barz.mp3', 2001, 'unknown2', 'pop'),
    ('Adore You', 'Harry Styles', '1.15', '/media/music/Harry Styles - Adore You.mp3', 2002, 'unknown3', 'hip-hop'),
    ('Watermelon Sugar', 'Harry Styles', '1.15', '/media/music/Harry Styles - Watermelon Sugar.mp3', 2002, 'unknown3', 'hip-hop'),
    ('Woman', 'Harry Styles', '1.15', '/media/music/Harry Styles - Woman.mp3', 2002, 'unknown3', 'hip-hop'),
    ('La femme ressort', 'Le Femme', '10.0', '/media/music/La Femme - La femme ressort.mp3', 2003, 'unknown4', 'dubstep'),
    ('Mycose', 'Le Femme', '10.0', '/media/music/La Femme - Mycose.mp3', 2003, 'unknown4', 'dubstep'),
    ('Paradigme', 'Le Femme', '10.0', '/media/music/La Femme - Paradigme.mp3', 2003, 'unknown4', 'dubstep'),
    ('Be the One', 'The Ting Tings', '3.0', '/media/music/The Ting Tings - Be the One.mp3', 2004, 'unknown5', 'progressive house'),
    ('Shut Up and Let Me Go', 'The Ting Tings', '3.0', '/media/music/The Ting Tings - Shut Up and Let Me Go.mp3', 2004, 'unknown5', 'progressive house'),
    ('We Walk', 'The Ting Tings', '3.0', '/media/music/The Ting Tings - We Walk.mp3', 2004, 'unknown5', 'progressive house'),
    ('Альтернатива', 'Дайте танк (!)', '4.35', '/media/music/Дайте танк (!) - Альтернатива.mp3', 2005, 'unknown6', 'trap'),
    ('Друг', 'Дайте танк (!)', '4.35', '/media/music/Дайте танк (!) - Друг.mp3', 2005, 'unknown6', 'trap'),
    ('Слова-паразиты', 'Дайте танк (!)', '4.35', '/media/music/Дайте танк (!) - Слова-паразиты.mp3', 2005, 'unknown6', 'trap'),
    ('Утро', 'Дайте танк (!)', '4.35', '/media/music/Дайте танк (!) - Утро.mp3', 2005, 'unknown6', 'trap')
